In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

/Users/Zalman/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


# array oriented programming

In [18]:
grades=[56,62,71,45,70]

In [25]:
newgrades=[]
for i in grades:
    new_g=np.sqrt(i)*10+15
    print(f'調整後成績:{new_g:.2f}')
    newgrades.append(new_g)

調整後成績:89.83
調整後成績:93.74
調整後成績:99.26
調整後成績:82.08
調整後成績:98.67


# 換成np.array來做

In [24]:
arr_grades=np.array(grades)

In [27]:
arr_grades

array([56, 62, 71, 45, 70])

In [28]:
np.sqrt(arr_grades)*10

array([74.83314774, 78.74007874, 84.26149773, 67.08203932, 83.66600265])

In [30]:
np.sqrt(arr_grades)*10+25

array([ 99.83314774, 103.74007874, 109.26149773,  92.08203932,
       108.66600265])

In [32]:
arr_new_grades=np.sqrt(arr_grades)*10+15
arr_new_grades

array([89.83314774, 93.74007874, 99.26149773, 82.08203932, 98.66600265])

In [33]:
arr_new_grades.mean()

92.71655323715235

In [34]:
arr_new_grades.std()

6.33540471768489

# brocasting

In [35]:
np.array([3,4,5,6,7])+5

array([ 8,  9, 10, 11, 12])

In [36]:
mygrades=np.array([89,99,60])

In [41]:
weights=np.array([0.3,0.4,0.3])

In [45]:
(mygrades*weights).sum()

84.3

In [46]:
np.dot(mygrades,weights)

84.3

In [47]:
mygrades@weights

84.3

# 不同shape轉換

### 0階array(0階tensor)

In [48]:
egg=94.87

### 1階array(1階tensor)

In [49]:
egg=np.array([9,4,8,7])

### 2階array(2階tensor)

In [53]:
A=np.array([[2,3,4],[4,5,6]])

In [54]:
A

array([[2, 3, 4],
       [4, 5, 6]])

In [55]:
B=np.array([3,9,6,12,8,20,1,10,7])

In [56]:
A.shape

(2, 3)

In [57]:
B.shape

(9,)

In [58]:
B.reshape(3,3)

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [59]:
B

array([ 3,  9,  6, 12,  8, 20,  1, 10,  7])

# ▴其實B未改變

In [60]:
B=B.reshape(3,3)

In [61]:
B

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [62]:
A@B

array([[ 46,  82, 100],
       [ 78, 136, 166]])

In [63]:
C=A@B

In [64]:
C

array([[ 46,  82, 100],
       [ 78, 136, 166]])

In [67]:
C[1]

array([ 78, 136, 166])

In [68]:
C[1,1]

136

# ▴記得Python從0開始，所以2的概念是1

In [69]:
C[:,2]

array([100, 166])