In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# array oriented programming

In [2]:
grades=[56,62,71,45,70]

In [3]:
newgrades=[]
for i in grades:
    new_g=np.sqrt(i)*10+15
    print(f'調整後成績:{new_g:.2f}')
    newgrades.append(new_g)

調整後成績:89.83
調整後成績:93.74
調整後成績:99.26
調整後成績:82.08
調整後成績:98.67


# 換成np.array來做

In [4]:
arr_grades=np.array(grades)

In [5]:
arr_grades

array([56, 62, 71, 45, 70])

In [6]:
np.sqrt(arr_grades)*10

array([74.83314774, 78.74007874, 84.26149773, 67.08203932, 83.66600265])

In [7]:
np.sqrt(arr_grades)*10+25

array([ 99.83314774, 103.74007874, 109.26149773,  92.08203932,
       108.66600265])

In [8]:
arr_new_grades=np.sqrt(arr_grades)*10+15
arr_new_grades

array([89.83314774, 93.74007874, 99.26149773, 82.08203932, 98.66600265])

In [9]:
arr_new_grades.mean()

92.71655323715235

In [10]:
arr_new_grades.std()

6.33540471768489

# brocasting

In [11]:
np.array([3,4,5,6,7])+5

array([ 8,  9, 10, 11, 12])

In [12]:
mygrades=np.array([89,99,60])

In [13]:
weights=np.array([0.3,0.4,0.3])

In [14]:
(mygrades*weights).sum()

84.3

In [15]:
np.dot(mygrades,weights)

84.3

In [16]:
mygrades@weights

84.3

# 不同shape轉換

### 0階array(0階tensor)

In [17]:
egg=94.87

### 1階array(1階tensor)

In [18]:
egg=np.array([9,4,8,7])

### 2階array(2階tensor)

In [19]:
A=np.array([[2,3,4],[4,5,6]])

In [20]:
A

array([[2, 3, 4],
       [4, 5, 6]])

In [21]:
B=np.array([3,9,6,12,8,20,1,10,7])

In [22]:
A.shape

(2, 3)

In [23]:
B.shape

(9,)

In [24]:
B.reshape(3,3)

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [25]:
B

array([ 3,  9,  6, 12,  8, 20,  1, 10,  7])

# ▴其實B未改變

In [26]:
B=B.reshape(3,3)

In [27]:
B

array([[ 3,  9,  6],
       [12,  8, 20],
       [ 1, 10,  7]])

In [28]:
A@B

array([[ 46,  82, 100],
       [ 78, 136, 166]])

In [29]:
C=A@B

In [30]:
C

array([[ 46,  82, 100],
       [ 78, 136, 166]])

In [31]:
C[1]

array([ 78, 136, 166])

In [32]:
C[1,1]

136

# ▴記得Python從0開始，所以2的概念是1

In [33]:
C[:,2]

array([100, 166])

In [34]:
X=np.array([3,9,1,3,-5,1,2])

In [35]:
X.reshape(len(X),1)

array([[ 3],
       [ 9],
       [ 1],
       [ 3],
       [-5],
       [ 1],
       [ 2]])

# array的filter功能

In [36]:
gd=np.array([59,30,25,65,60,100,85,8])

In [37]:
passed=np.array([False,False,False,True,True,True,True,False])

In [38]:
gd[passed]

array([ 65,  60, 100,  85])

In [41]:
gd[gd>=60]

array([ 65,  60, 100,  85])

In [42]:
(gd>=60)&(gd<80)

array([False, False, False,  True,  True, False, False, False])